[2024-07-07T11:38:30.086+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T11:38:30.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.starting manual__2024-07-07T11:38:23.357633+00:00 [queued]>
[2024-07-07T11:38:30.127+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.starting manual__2024-07-07T11:38:23.357633+00:00 [queued]>
[2024-07-07T11:38:30.128+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-07T11:38:30.145+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): starting> on 2024-07-07 11:38:23.357633+00:00
[2024-07-07T11:38:30.153+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T11:38:30.155+0000] {standard_task_runner.py:63} INFO - Started process 66 to run task
[2024-07-07T11:38:30.155+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'starting', 'manual__2024-07-07T11:38:23.357633+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpky519rcz']
[2024-07-07T11:38:30.157+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask starting
[2024-07-07T11:38:30.209+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.starting manual__2024-07-07T11:38:23.357633+00:00 [running]> on host 33ecc1cdac44
[2024-07-07T11:38:30.316+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='starting' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T11:38:23.357633+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T11:38:23.357633+00:00'
[2024-07-07T11:38:30.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T11:38:30.318+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-07T11:38:30.319+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Chuẩn bị cào dữ liệu"']
[2024-07-07T11:38:30.332+0000] {subprocess.py:86} INFO - Output:
[2024-07-07T11:38:30.334+0000] {subprocess.py:93} INFO - Chuẩn bị cào dữ liệu
[2024-07-07T11:38:30.335+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-07T11:38:30.336+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T11:38:30.367+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=starting, run_id=manual__2024-07-07T11:38:23.357633+00:00, execution_date=20240707T113823, start_date=20240707T113830, end_date=20240707T113830
[2024-07-07T11:38:30.411+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T11:38:30.442+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-07-07T11:38:30.446+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
